apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres
          name: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
            - name: data
              mountPath: /var/lib/postgresql
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: gitea
          resources:
            limits:
              cpu: "4"
              memory: 512Mi
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
        - name: data
          hostPath:
            path: /root/data/postgres
