apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
data:
  CONSUL_ADDR: 192.168.119.143

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-gateway
  name: app-gateway
spec:
  ports:
    - port: 80
      name: web
      protocol: TCP
    - port: 443
      name: web-secure
      protocol: TCP
  selector:
    app: app-gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-gateway
  name: app-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gateway
  template:
    metadata:
      labels:
        app: app-gateway
    spec:
      containers:
        - image: openresty/openresty
          name: app-gateway
          envFrom:
            - configMapRef:
                name: gateway
          ports:
            - name: web
              containerPort: 80
            - name: web-secure
              containerPort: 443
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
            - name: lua
              mountPath: /usr/local/openresty/nginx/conf
          resources:
            limits:
              cpu: "4"
              memory: 512Mi
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
        - name: lua
          hostPath:
            path: /root/app-gateway

