apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-gateway
  name: app-gateway
spec:
  ports:
    - port: 80
      name: web
      protocol: TCP
    - port: 443
      name: web-secure
      protocol: TCP
  selector:
    app: app-gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-gateway
  name: app-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gateway
  template:
    metadata:
      labels:
        app: app-gateway
    spec:
      containers:
        - image: localhost:5000/app-gateway
          name: app-gateway
          ports:
            - name: web
              containerPort: 80
            - name: web-secure
              containerPort: 443
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
          resources:
            limits:
              cpu: "64m"
              memory: 512Mi
            requests:
              cpu: 6m
              memory: 8Mi
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime