version: '3'

services:
  gw_openresty:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gw
  consul1: 
    image: consul:latest
    container_name: consul1
    restart: always
    network_mode: mynet
    command: agent -server -client=0.0.0.0 -bootstrap-expect=3 -node=consul1 -datacenter=dc1 -ui
    networks:
      - gw


networks:
  gw:
    driver: host
