version: '3'

services:
  gw_openresty:
    image: openresty/openresty
    container_name: openresty
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/usr/local/openresty/nginx/conf
      - /data/openresty:/usr/local/openresty/nginx/logs
    ports: ["8000:8000", "443:443", "80:80"]
    network_mode: host

