version: '3'

services:
  gw_openresty:
    image: openresty/openresty
    container_name: openresty
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/app-gateway:/usr/local/openresty/nginx/conf
      - /data/openresty:/usr/local/openresty/nginx/logs
    network_mode: host
