apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: gitea
spec:
  ports:
    - port: 3000
  selector:
    app: gitea
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - image: gitea/gitea
          name: gitea
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
            - name: data
              mountPath: /data/gitea
          env:
            - name: "GITEA__database__DB_TYPE"
              value: "postgres"
            - name: "GITEA__database__HOST"
              value: "10.43.50.211:5432"
            - name: "GITEA__database__NAME"
              value: "gitea"
            - name: "GITEA__database__USER"
              value: "postgres"
            - name: "GITEA__database__PASSWD"
              value: "postgres"
          resources:
            limits:
              cpu: "64m"
              memory: 512Mi
            requests:
              cpu: 6m
              memory: 8Mi
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
        - name: data
          hostPath:
            path: /root/data/gitea
