version: '3'

networks:
  monitor:

services:
  node-exporter: # dashboard: 8919
    image: prom/node-exporter:latest
    container_name: "node-exporter"
    ports:
      - "9100:9100"
    networks:
      - monitor
  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
    networks:
      - monitor
  grafana:
    image: grafana/grafana
    container_name: "grafana"
    networks:
      - monitor
    ports:
      - "3000:3000"
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - monitor
